on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: ["1.19"]
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    name: Run ${{ matrix.go }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Restore cache"
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: |
        go test -race -v ./...
